apiVersion: v1
kind: Pod
metadata:
  labels:
    managed-by: tm-installer
  name: platform-install-pod
  namespace: default
spec:
  containers:
    - args:
        - -wait_file
        - /tekton/downward/ready
        - -wait_file_content
        - -post_file
        - /tekton/tools/0
        - -entrypoint
        - sh
        - --
        - -c
        - sleep 3 && touch foo
      command:
        - /tekton/tools/entrypoint
      env:
        - name: HOME
          value: /tekton/home
      image: index.docker.io/library/busybox@sha256:edafc0a0fb057813850d1ba44014914ca02d671ae247107ca70c94db686e7de6
      imagePullPolicy: IfNotPresent
      name: step-unnamed-0
      resources:
        requests:
          cpu: "0"
          ephemeral-storage: "0"
          memory: "0"
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /tekton/tools
          name: tools
        - mountPath: /tekton/downward
          name: downward
        - mountPath: /workspace
          name: workspace
        - mountPath: /tekton/home
          name: tekton-home
        - mountPath: /builder/home
          name: tekton-home
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-rcd4v
          readOnly: true
      workingDir: /workspace
    - args:
        - -wait_file
        - /tekton/tools/0
        - -post_file
        - /tekton/tools/1
        - -entrypoint
        - sh
        - --
        - -c
        - ls
        - foo
      command:
        - /tekton/tools/entrypoint
      env:
        - name: HOME
          value: /tekton/home
      image: index.docker.io/library/busybox@sha256:edafc0a0fb057813850d1ba44014914ca02d671ae247107ca70c94db686e7de6
      imagePullPolicy: IfNotPresent
      name: step-unnamed-1
      resources:
        requests:
          cpu: "0"
          ephemeral-storage: "0"
          memory: "0"
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /tekton/tools
          name: tools
        - mountPath: /workspace
          name: workspace
        - mountPath: /tekton/home
          name: tekton-home
        - mountPath: /builder/home
          name: tekton-home
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-rcd4v
          readOnly: true
      workingDir: /workspace
  initContainers:
    - command:
        - cp
        - /ko-app/entrypoint
        - /tekton/tools/entrypoint
      image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.9.2@sha256:83b4e08d7117fb1eae593d4f79ea7a0b548ce8dd8dca7029d554b3fbf9610274
      imagePullPolicy: IfNotPresent
      name: prepare
      volumeMounts:
        - mountPath: /tekton/tools
          name: tools
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-rcd4v
          readOnly: true
  restartPolicy: Never

  volumes:
    - emptyDir: {}
      name: workspace
    - emptyDir: {}
      name: tekton-home
    - emptyDir: {}
      name: tools